[package]
name = "northstar"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
tempfile = "3.2"

[workspace]
members = ["."]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
